// AUTOGENERATED - DO NOT MODIFY
import PaymentDisputeView from '../src/views/PaymentDisputeView';import DisputeListView from '../src/views/DisputeListView';import AppSettings from '../src/views/AppSettings';

export * from '@stripe/ui-extension-sdk/version';
export const BUILD_TIME = '2026-04-20 21:40:46.629754 -0700 PDT m=+7.356487376';

export { 
  PaymentDisputeView,

  DisputeListView,

  AppSettings
 };

export default {
  "$schema": "https://stripe.com/stripe-app.schema.json",
  "distribution_type": "PRIVATE",
  "icon": "./src/assets/winback_logo.png",
  "id": "com.jkbtech.winback",
  "name": "WinBack",
  "permissions": [
    {
      "permission": "dispute_read",
      "purpose": "Read dispute details to guide merchants through the response process"
    },
    {
      "permission": "dispute_write",
      "purpose": "Submit evidence and responses on behalf of the merchant"
    },
    {
      "permission": "charge_read",
      "purpose": "Read charge details associated with disputes"
    },
    {
      "permission": "customer_read",
      "purpose": "Read customer information for dispute context"
    },
    {
      "permission": "file_read",
      "purpose": "Read uploaded evidence files"
    },
    {
      "permission": "file_write",
      "purpose": "Upload evidence files for dispute responses"
    },
    {
      "permission": "payment_intent_read",
      "purpose": "Read payment intent details for dispute context"
    }
  ],
  "post_install_action": {
    "type": "settings"
  },
  "ui_extension": {
    "content_security_policy": {
      "connect-src": [
        "https://winbackpay.com/api/"
      ],
      "purpose": "Backend API calls to WinBack services for dispute guidance, AI narrative generation, evidence metadata, and billing."
    },
    "views": [
      {
        "component": "PaymentDisputeView",
        "viewport": "stripe.dashboard.payment.detail"
      },
      {
        "component": "DisputeListView",
        "viewport": "stripe.dashboard.drawer.default"
      },
      {
        "component": "AppSettings",
        "viewport": "settings"
      }
    ]
  },
  "version": "1.0.1"
};
