// AUTO-GENERATED by scripts/sync-version.cjs. Do not edit.
// Source of truth: stripe-app/stripe-app.json
// Regenerated on every `npm run upload` or `npm start` via the
// preupload/prestart hooks in package.json.

export const APP_VERSION = '1.1.9';
