#!/usr/bin/env node
/**
 * Sync src/lib/version.ts with the version in stripe-app.json.
 *
 * Stripe Apps SDK does not expose the installed manifest version at runtime
 * (ExtensionContextValue has no version field), so any version string we
 * render in the iframe has to be baked in at build time. This script keeps
 * a generated TypeScript constant in lockstep with stripe-app.json so the
 * "About WinBack" line in Settings cannot drift from the manifest version.
 *
 * v1.1.6 was rejected from the Stripe Marketplace specifically for that
 * drift (manifest said 1.1.6, AppSettings said "Version 0.0.1"). This is
 * the programmatic guard against the same class of bug.
 *
 * Wired into package.json's preupload + prestart hooks so it runs before
 * any code path that bundles for the iframe. Must be invoked via npm
 * (`npm run upload`, `npm start`) -- running `stripe apps upload` directly
 * bypasses the hook and is no longer the recommended workflow.
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const manifestPath = path.join(root, 'stripe-app.json');
const versionFile = path.join(root, 'src', 'lib', 'version.ts');

const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
if (!manifest.version || typeof manifest.version !== 'string') {
  console.error('[sync-version] stripe-app.json has no version field');
  process.exit(1);
}

const generated = `// AUTO-GENERATED by scripts/sync-version.cjs. Do not edit.
// Source of truth: stripe-app/stripe-app.json
// Regenerated on every \`npm run upload\` or \`npm start\` via the
// preupload/prestart hooks in package.json.

export const APP_VERSION = '${manifest.version}';
`;

const existing = fs.existsSync(versionFile)
  ? fs.readFileSync(versionFile, 'utf8')
  : '';

if (existing === generated) {
  console.log(`[sync-version] src/lib/version.ts already at ${manifest.version}`);
} else {
  fs.mkdirSync(path.dirname(versionFile), { recursive: true });
  fs.writeFileSync(versionFile, generated);
  console.log(`[sync-version] wrote APP_VERSION = '${manifest.version}'`);
}
